src/WebAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
      
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/WebAPI/Controllers/ToDoController.cs
using Core;
using Core.Entities;
using SharedKernel.Interfaces;
using Web.ApiModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IRepository _repository;

        public ToDoController(IRepository repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            var items = (await _repository.ListAsync<ToDoItem>())
                            .Select(ToDoItemDTO.FromToDoItem);
            return View(items);
        }

        public IActionResult Populate()
        {
            int recordsAdded = DatabasePopulator.PopulateDatabase(_repository);
            return Ok(recordsAdded);
        }
    }
}

src/WebAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "FA.LegalHCM";
}

<div class="row">
    <div class="col-md-6">
        <h2>To Do Items (MVC)</h2>
        <ul>
            <li><a asp-area="" asp-controller="ToDo" asp-action="Populate">Load Sample To Do Items</a> (API call returning just a number)</li>
            <li><a asp-area="" asp-controller="ToDo" asp-action="Index">List To Do Items</a></li>
            <li><a href="/swagger">API Documentation (Swagger)</a></li>
        </ul>
    </div>
</div>

src/WebAPI/Views/ToDo/Index.cshtml
@{
    ViewData["Title"] = "ToDo List";
}
@model IEnumerable<Web.ApiModels.ToDoItemDTO>
<h2>To Do Items (MVC View)</h2>
<ul>
@foreach (var item in Model)
{
    <li>@item.Title<br/>@item.Description</li>
}
</ul>